#!/usr/bin/env bash
# Usage: sub example advanced expert case-select
# Summary: BASH Case Select Example
# Help: This is an example of a BASH Case Select

set -e

# Provide sub completions
if [ "$1" = "--complete" ]; then
  echo --name
  echo --break
  exit
fi

what="counter"
break_on=6
while [ ! "$1" == "" ]; do
	case "$1" in
		--name)
			if [[ ! "$2" == -* ]]; then
				name=$2
				shift
			else
				name="default"
			fi
		;;
		--break) 
			if [[ ! "$2" == -* ]]; then
				break_on=$2
				shift
			else
				break_on=3
			fi
		;;
	esac

	shift
done

echo "-=> Executing Case Select Example"
echo "----> Breaking on $break_on"
echo "----> Counter is called $name"

COUNTER=0
while [ $COUNTER -lt 5 ]; do
	echo "------> The $name is $COUNTER"
	COUNTER=`expr $COUNTER + 1`

	if [ "$break_on" == "$COUNTER" ]; then
		break
	fi
done

echo "- Finished..."