#!/usr/bin/env bash
# Usage: sub example [command]
# Summary: Collection of BASH Sub Example Scripts
# Help: These commands are mostly used as examples and for testing sub modifications

set -e

sub help example