#!/usr/bin/env bash
set -e

print=""
if [ "$1" = "-" ]; then
  print=1
  shift
fi

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshenv'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load sub automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo "eval \"\$(${_SUB_ROOT}/bin/sub init -)\""
    echo
  } >&2

  exit 1
fi

echo "export PATH=\"\${PATH}:${_SUB_ROOT}/bin\""

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/sub.${shell}\""
  ;;
esac

wrapper_function=
# hack for bash where numbers are not valid function name
[ "$shell" = "bash" ] && wrapper_function=_sub_wrapper

commands=(`sub commands --sh`)
IFS="|"
cat <<EOS
${wrapper_function:-sub}() {
  local command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`sub "sh-\$command" "\$@"\`;;
  *)
    command sub "\$command" "\$@";;
  esac
}
EOS

# related to the bash hack above
[ -n "$wrapper_function" ] && echo "alias sub=${wrapper_function}"
