#!/usr/bin/env bash
set -e

print_summaries() {
  local sub_commands="$(sub commands)"
  local commands=()
  local summaries=()
  local longest_command=0
  local command

  if [[ "$0" == *help ]]; then
    sub_commands="$(sub commands $_SUB_COMMAND_VARS)"
    if [ -f "$sub_commands" ]; then
      print_help $sub_commands
      exit
    fi
  fi

  for command in ${sub_commands[@]}; do
    local file="$(command_path "$command")"
    if [ ! -h "$file" ] && [ -f "$file" ]; then
      local summary="$(summary "$file")"
      if [ -n "$summary" ]; then

        if [ -d "$_SUB_COMMAND_ROOT/sub-$command" ]; then
          commands["${#commands[@]}"]="-> $command"
        else
          commands["${#commands[@]}"]="$command"
        fi

        summaries["${#summaries[@]}"]="$summary"

        if [ "${#command}" -gt "$longest_command" ]; then
          longest_command=`expr ${#command} + 3`
        fi
      fi
    fi
  done

  local index
  local columns="$(tput cols)"
  local summary_length=$(( $columns - $longest_command - 5 ))

  for (( index=0; index < ${#commands[@]}; index++ )); do
    printf "   %-${longest_command}s  %s\n" "${commands[$index]}" \
      "$(truncate "$summary_length" "${summaries[$index]}")"
  done
}

print_help() {
  local file="$1"
  local usage="$(usage "$file")"

  if [ -n "$usage" ]; then
    echo "$usage"

    local help="$(help "$file")"
    [ -n "$help" ] && echo && echo "$help"
  else
    echo "Sorry, this command isn't documented yet."
  fi
}

command_path() {
  sub_path="$(command -v "sub-$command" || command -v "sub-sh-$command" || true)"
  if [ "$sub_path" == "" ] && [ -f "$_SUB_COMMAND_ROOT/sub-$command/sub-$command" ]; then
    echo "$_SUB_COMMAND_ROOT/sub-$command/sub-$command"
  else
    echo "$sub_path"
  fi
}

summary() {
  sed -n "s/^# Summary: \(.*\)/\1/p" "$1"
}

usage() {
  sed -n "s/^# \(Usage: .*\)/\1/p" "$1"
}

help() {
  awk '/^[^#]/{p=0} /^# Help:/{p=1} p' "$1" | sed "s/^# Help: //;s/^# //;s/^#//"
}

truncate() {
  local max_length="$1"
  local string="$2"

  if [ "${#string}" -gt "$max_length" ]; then
    local length=$(( $max_length - 3 ))
    echo "${string:0:$length}..."
  else
    echo "$string"
  fi
}

# Provide sub completions
if [ "$1" = "--complete" ]; then
  exec "sub-commands"
  exit
fi

command="$_SUB_COMMAND_FILE"
if [ "$command" == "" ] || [ "$command" == "help" ] || [[ "$_SUB_COMMAND_ROOT" == *sub-$_SUB_COMMAND_FILE ]]; then
echo "Usage: sub <command> [<args>]

Some useful sub commands are:
$(print_summaries)

See 'sub help <command>' for information on a specific command."
else
  file="$(command_path "$command")"

  if [ -n "$file" ]; then
    print_help "$file"
  else
    echo "sub: no such command \`$command'" >&2
    exit 1
  fi
fi
