#!/usr/bin/env bash
set -e

print_summaries() {
  for file in $_SUB_ROOT/libexec/sub-*; do
    if [ ! -h $file ]; then
      local summary=$(sed -n "s/^# Summary: \(.*\)/\1/p" "$file")
      if [ -n "$summary" ]; then
        local name=$(basename $file | sed 's/sub-//')
        awk -v name="$name" 'BEGIN {printf "   %-20s   ", name}'
        echo -n $summary
        echo
      fi
    fi
  done
}

print_help() {
  local usage=$(sed -n "s/^# \(Usage: .*\)/\1/p" "$1")
  local halp=$(awk '/^[^#]/{p=0} /^# Help:/{p=1} p' "$1" | sed "s/^# Help: //;s/^# //;s/^#//")

  if [ -n "$usage" ]; then
    echo $usage
    [ -n "$halp" ] && echo && echo "$halp"
  else
    echo "Sorry, this command isn't documented yet."
  fi
}

# Provide sub completions
if [ "$1" = "--complete" ]; then
  exec "sub-commands"
  exit
fi

case "$1" in
"") echo "Usage: sub <command> [<args>]

Some useful sub commands are:
$(print_summaries)

See 'sub help <command>' for information on a specific command."
;;
*)
  command_path="$(command -v "$_SUB_ROOT/libexec/sub-$1" || true)"
  if [ -n "$command_path" ]; then
    print_help "$_SUB_ROOT/libexec/sub-$1"
  else
    echo "sub: no such command \`$1'"
  fi
esac
